/**
 * Agent command — Scaffold and manage custom agents for the agent-baba-d platform.
 *
 * Usage:
 *   buff agent create <name>    — Create a new custom agent project from a template
 *   buff agent list             — List all discovered custom agent plugins
 *   buff agent info <name>      — Show details about a discovered agent plugin
 *
 * The `buff agent create` command scaffolds a new project using the @agent-baba-d/sdk
 * package, providing a ready-to-develop custom agent with:
 * - package.json with SDK dependency
 * - TypeScript configuration
 * - Agent base class implementation
 * - Vitest test setup with testing utilities
 * - README with instructions
 */

import { Command } from 'commander';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import inquirer from 'inquirer';

import { BaseCommand } from './commands.js';
import { discoverAgentPlugins, getPluginStats } from '../plugins/agent-plugin.js';
import { logger } from '../utils/logger.js';

// ─── Agent Template ─────────────────────────────────────────────────────────

interface AgentProjectFiles {
  [path: string]: string;
}

function generateAgentProject(name: string, agentName: string, description: string): AgentProjectFiles {
  const className = toPascalCase(agentName);

  return {
    'package.json': JSON.stringify({
      name: name.toLowerCase().replace(/\s+/g, '-'),
      version: '1.0.0',
      description: `Custom agent-baba-d agent: ${description}`,
      type: 'module',
      main: './dist/agent.js',
      scripts: {
        build: 'tsc',
        test: 'vitest run',
        'test:watch': 'vitest',
        dev: 'tsc --watch',
      },
      dependencies: {
        '@agent-baba-d/sdk': '^1.0.0',
      },
      devDependencies: {
        typescript: '^5.3.0',
        vitest: '^4.1.0',
        '@types/node': '^20.11.0',
      },
    }, null, 2),
    'tsconfig.json': JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        esModuleInterop: true,
        strict: true,
        outDir: './dist',
        rootDir: './src',
        declaration: true,
        skipLibCheck: true,
      },
      include: ['src'],
    }, null, 2),
    'src/agent.ts': `import { Agent, type AgentContext, type AgentResult, type LLMCallFn } from '@agent-baba-d/sdk';

/**
 * ${className} — ${description}
 *
 * Generated by \`buff agent create ${name}\`
 */
export class ${className} extends Agent {
  readonly name = '${className}';
  readonly description = '${description}';

  async execute(context: AgentContext, callLLM: LLMCallFn): Promise<AgentResult> {
    // Read artifacts (files) from the shared context
    const fileContext = context.artifacts
      .map((a) => \`--- \${a.path} ---\\n\${a.content}\`)
      .join('\\n\\n');

    // Build a prompt for the LLM
    const prompt = [
      '## Goal',
      context.goal,
      '',
      '## Context',
      fileContext || '(No files in context)',
      '',
      '## Instructions',
      'Analyze the above and provide your output.',
      '',
      'Return your response as plain text with clear sections.',
    ].join('\\n');

    // Call the LLM (the orchestrator injects the provider/model)
    const response = await callLLM(prompt, {
      temperature: 0.7,
      maxTokens: 2048,
    });

    return {
      success: true,
      summary: \`Processed goal: \${context.goal.slice(0, 60)}\`,
      details: response,
    };
  }
}
`,
    'tests/agent.test.ts': `import { describe, it, expect } from 'vitest';
import {
  createTestContext,
  createMockCallLLM,
  assertAgentResult,
} from '@agent-baba-d/sdk/testing';
import { ${className} } from '../src/agent.js';

describe('${className}', () => {
  it('should execute successfully', async () => {
    const agent = new ${className}();
    const context = createTestContext('Write a test');
    const callLLM = createMockCallLLM('Test output: success');

    const result = await agent.execute(context, callLLM);
    assertAgentResult(result);
    expect(result.summary).toBeTruthy();
  });

  it('should include context artifacts in the prompt', async () => {
    const agent = new ${className}();
    const context = createTestContext('Review code');
    context.artifacts.push({
      path: 'example.ts',
      content: 'const x = 1;',
      description: 'Example file',
    });

    let receivedPrompt = '';
    const callLLM = createMockCallLLM((prompt: string) => {
      receivedPrompt = prompt;
      return 'Analysis complete.';
    });

    await agent.execute(context, callLLM);
    expect(receivedPrompt).toContain('example.ts');
    expect(receivedPrompt).toContain('const x = 1;');
  });

  it('should handle errors gracefully', async () => {
    const agent = new ${className}();
    const context = createTestContext('Test error handling');
    const callLLM = async () => { throw new Error('API error'); };

    const result = await agent.execute(context, callLLM);
    // Agent should not crash — it should return a failure result
    expect(result).toBeDefined();
  });
});
`,
    'vitest.config.ts': `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['tests/**/*.test.ts'],
  },
});
`,
    '.gitignore': `node_modules/
dist/
.env
`,
    'README.md': `# ${name}

${description}

## Installation

\`\`\`bash
npm install
\`\`\`

## Build

\`\`\`bash
npm run build
\`\`\`

## Test

\`\`\`bash
npm test
\`\`\`

## Usage in agent-baba-d

Place the compiled agent in \`~/.buff/agents/\`:

\`\`\`bash
cp dist/agent.js ~/.buff/agents/${name}.js
\`\`\`

Then run \`buff plugins list\` to see it auto-discovered.

## License

MIT
`,
  };
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

// ─── AgentCommand ───────────────────────────────────────────────────────────

export class AgentCommand extends BaseCommand {
  create(): Command {
    const command = new Command('agent')
      .description('Scaffold and manage custom agent-baba-d agents');

    // ── create ─────────────────────────────────────────────────────────────
    command
      .command('create')
      .description('Create a new custom agent project from a template')
      .argument('[name]', 'Agent project name (e.g., "my-code-reviewer")')
      .option('-n, --agent-name <name>', 'Agent class name (defaults to project name in PascalCase)')
      .option('-d, --description <desc>', 'Agent description', 'A custom agent-baba-d agent')
      .option('--dir <path>', 'Output directory (defaults to ./<name>)')
      .action(async (name?: string, options?: {
        agentName?: string;
        description?: string;
        dir?: string;
      }) => {
        await this.createAgent(name, options || {});
      });

    // ── list ───────────────────────────────────────────────────────────────
    command
      .command('list')
      .description('List all discovered custom agent plugins')
      .action(async () => {
        await this.listAgents();
      });

    // ── info ───────────────────────────────────────────────────────────────
    command
      .command('info')
      .description('Show details about a discovered agent plugin')
      .argument('<name>', 'Agent name (as shown in buff agent list)')
      .action(async (name: string) => {
        await this.showAgentInfo(name);
      });

    return command;
  }

  // ── Action Handlers ──────────────────────────────────────────────────────

  private async createAgent(
    name?: string,
    options?: {
      agentName?: string;
      description?: string;
      dir?: string;
    },
  ): Promise<void> {
    let projectName = name;
    if (!projectName) {
      const answer = await inquirer.prompt<{ name: string }>([{
        type: 'input',
        name: 'name',
        message: 'Agent project name:',
        default: 'my-custom-agent',
        validate: (input: string) => {
          if (!input.trim()) return 'Name is required';
          if (!/^[a-z0-9-]+$/.test(input.trim())) return 'Use only lowercase letters, numbers, and hyphens';
          return true;
        },
      }]);
      projectName = answer.name.trim();
    }

    const agentName = options?.agentName || projectName;
    const description = options?.description || 'A custom agent-baba-d agent';
    const projectDir = options?.dir || join(process.cwd(), projectName);

    if (existsSync(projectDir)) {
      logger.error(`Directory already exists: ${projectDir}`);
      return;
    }

    logger.info(`Creating agent project '${projectName}'...`);

    try {
      const files = generateAgentProject(projectName, agentName, description);

      for (const [filePath, content] of Object.entries(files)) {
        const fullPath = join(projectDir, filePath);
        const dir = filePath.includes('/') ? join(projectDir, ...filePath.split('/').slice(0, -1)) : projectDir;
        if (!existsSync(dir)) {
          mkdirSync(dir, { recursive: true });
        }
        writeFileSync(fullPath, content, 'utf-8');
      }

      logger.success(`Created agent project: ${projectName}`);
      console.log('');
      console.log('  📁 Project structure:');
      console.log(`     ${projectName}/`);
      console.log(`     ├── package.json`);
      console.log(`     ├── tsconfig.json`);
      console.log(`     ├── vitest.config.ts`);
      console.log(`     ├── .gitignore`);
      console.log(`     ├── README.md`);
      console.log(`     └── src/`);
      console.log(`         └── agent.ts`);
      console.log(`     └── tests/`);
      console.log(`         └── agent.test.ts`);
      console.log('');
      console.log('  📋 Next steps:');
      console.log(`     cd ${projectName}`);
      console.log('     npm install');
      console.log('     npm test');
      console.log('     npm run build');
      console.log('     cp dist/agent.js ~/.buff/agents/');
      console.log('');
      logger.info('Edit src/agent.ts to implement your custom agent logic.');
    } catch (err) {
      logger.error(`Failed to create agent project: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  private async listAgents(): Promise<void> {
    const stats = getPluginStats();

    logger.highlight('═'.repeat(60));
    logger.highlight('  🤖  Custom Agent Plugins');
    logger.highlight('═'.repeat(60));

    if (stats.agentPlugins === 0) {
      console.log('\n  (no custom agent plugins found)');
      console.log('  Tip: Place compiled .js agent files in ~/.buff/agents/');
      console.log('  Tip: Use `buff agent create <name>` to scaffold a new agent');
      console.log('');
      return;
    }

    try {
      const plugins = await discoverAgentPlugins();
      console.log(`\n  Found ${plugins.size} agent plugin(s):`);
      console.log('');

      for (const [agentType, plugin] of plugins) {
        const meta = plugin.metadata;
        console.log(`  🤖 ${meta.name} v${meta.version}`);
        console.log(`     ${meta.description}`);
        console.log(`     Agent types: ${meta.agentTypes.join(', ')}`);
        if (meta.author) {
          console.log(`     Author: ${meta.author}`);
        }
        console.log(`     → Registered as: ${agentType}`);
        console.log('');
      }
    } catch (err) {
      logger.error(`Failed to list agent plugins: ${err}`);
    }
  }

  private async showAgentInfo(name: string): Promise<void> {
    try {
      const plugins = await discoverAgentPlugins();
      const matching = [...plugins.entries()].filter(
        ([, p]) =>
          p.metadata.name.toLowerCase().includes(name.toLowerCase()) ||
          p.metadata.agentTypes.some((t) => t.toLowerCase().includes(name.toLowerCase())),
      );

      if (matching.length === 0) {
        logger.error(`No agent plugin found matching '${name}'`);
        logger.info('Run `buff agent list` to see all available agents.');
        return;
      }

      for (const [agentType, plugin] of matching) {
        const meta = plugin.metadata;
        logger.highlight('═'.repeat(60));
        logger.highlight(`  🤖  ${meta.name} v${meta.version}`);
        logger.highlight('═'.repeat(60));
        console.log(`  Description: ${meta.description}`);
        console.log(`  Agent Types: ${meta.agentTypes.join(', ')}`);
        if (meta.author) console.log(`  Author: ${meta.author}`);
        console.log(`  Registered As: ${agentType}`);
        console.log('');
      }
    } catch (err) {
      logger.error(`Failed to get agent info: ${err}`);
    }
  }
}
