import { Command } from 'commander';
import { existsSync, statSync } from 'node:fs';
import ora from 'ora';
import { BaseCommand } from './commands.js';
import { ContextParser } from '../context/parser.js';
import { logger } from '../utils/logger.js';

/**
 * Plan command — generate implementation plans for code changes
 * buff plan <directory> [--provider openrouter] [--task "add user auth"]
 */
export class PlanCommand extends BaseCommand {
  create(): Command {
    const command = new Command('plan')
      .description('Generate an implementation plan for a codebase task')
      .argument('[target]', 'File or directory to plan for', '.')
      .option('-t, --task <text>', 'Description of the task to plan')
      .option('-p, --provider <provider>', 'Inference provider')
      .option('-m, --model <model>', 'Model to use')
      .option('-v, --verbose', 'Show full context being sent to the model')
      .action(async (target: string, options?: { task?: string; provider?: string; model?: string; verbose?: boolean }) => {
        await this.execute(target, options || {});
      });

    return command;
  }

  private async execute(target: string, options?: { task?: string; provider?: string; model?: string; verbose?: boolean }): Promise<void> {
    const { type, provider } = this.getProvider(options || {});

    const available = await provider.isAvailable();
    if (!available) {
      logger.error(`${provider.name} is not available. Check your configuration.`);
      return;
    }

    const task = options?.task || 'Analyze the codebase and suggest improvements';

    const parser = new ContextParser({
      maxTokens: 4096,
      priorityPatterns: ['package.json', 'tsconfig.json', 'index.ts', 'main.ts', 'README.md'],
    });

    let contextStr: string;

    const spinner = ora('Analyzing codebase...').start();

    try {
      if (existsSync(target) && statSync(target).isDirectory()) {
        const context = await parser.parseFromDirectory(target);
        contextStr = ContextParser.formatContext(context);
      } else if (existsSync(target)) {
        const context = parser.parseFromFiles([target]);
        contextStr = ContextParser.formatContext(context);
      } else {
        spinner.stop();
        logger.error(`Target not found: ${target}`);
        return;
      }

      if (options?.verbose) {
        spinner.stop();
        logger.highlight('\n--- Context Sent to Model ---\n');
        console.log(contextStr.slice(0, 2000) + (contextStr.length > 2000 ? '\n\n[...truncated...]' : ''));
        logger.highlight('\n--- End Context ---\n');
        spinner.start('Generating plan...');
      }

      const prompt = `You are a senior software engineer. Given the following codebase context, create a detailed implementation plan for this task:

## Task
${task}

## Codebase Context
${contextStr}

## Plan Requirements
Please provide:
1. **Summary** — Brief overview of the task
2. **Files to Modify** — List each file with specific changes needed
3. **Architecture Changes** — Any new files, modules, or structural changes
4. **Implementation Steps** — Ordered step-by-step guide
5. **Potential Risks** — Edge cases, breaking changes, or considerations
6. **Testing Strategy** — How to verify the changes work

Use clear markdown formatting.`;

      spinner.text = 'Generating plan...';

      const result = await provider.generate(prompt, options);

      spinner.stop();

      console.log(`\n${'='.repeat(60)}`);
      logger.highlight(`📋 Implementation Plan`);
      console.log(`${'='.repeat(60)}\n`);
      console.log(result);
      console.log(`\n${'='.repeat(60)}`);
      logger.info(`Generated by ${provider.name}`);
    } catch (err) {
      spinner.fail('Planning failed');
      logger.error(String(err));
    }
  }
}
