/**
 * END-TO-END — a HYBRID ask: "a web-based interactive book with narration".
 *
 * Drives the REAL Orchestrator (real reasoner, real planner, real composite
 * phase planner, real writer prose path, real writer code path, real runner,
 * real file writes, real ledger) with only the model scripted. The scripted
 * reasoner/planner return the same HOSTILE Python-plan answers the live audit
 * captured, because the point of G12 is that the agent's structure must not be
 * able to deliver "a script that writes the book" for an ask like this.
 *
 * What it pins:
 *   1. the deliverable is planned as PHASES (shape → content → experience →
 *      services → verify), not as one class;
 *   2. the CONTENT is written as prose units — a website with an empty shell
 *      and no chapters is a non-delivery;
 *   3. the OPTIONAL Python narration script is produced but is NOT the only
 *      path to narration;
 *   4. the VERIFY step is generated by us, runs for real, and FAILS while the
 *      deliverable is incomplete — so the run cannot report a green result over
 *      a half-built artifact;
 *   5. the run hands back `pendingWork`, so the work continues unattended
 *      instead of asking the user to say "continue".
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach, vi } from 'vitest';
import { mkdtempSync, rmSync, mkdirSync, existsSync, readFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { Orchestrator } from '../../src/agents/orchestrator.js';
import { ProviderFactory } from '../../src/inference/factory.js';
import { resetWorkspaceStore } from '../../src/config/workspace.js';
import { clearLongFormJobs, countWords, findLatestJob } from '../../src/learning/long-form.js';
import { clearUnattendedJobs } from '../../src/learning/unattended-job.js';

const root = mkdtempSync(join(tmpdir(), 'buff-webbook-e2e-'));
const cfgDir = join(root, '.nuvira');
const memDir = join(root, '.nuvira', 'memory');
const projectDir = join(root, 'book-project');
const ORIG_CONFIG_DIR = process.env.NUVIRA_CONFIG_DIR;
const ORIG_MEMORY_DIR = process.env.NUVIRA_MEMORY_DIR;
const ORIG_CWD = process.cwd();

beforeAll(() => {
  mkdirSync(memDir, { recursive: true });
  mkdirSync(projectDir, { recursive: true });
  process.env.NUVIRA_CONFIG_DIR = cfgDir;
  process.env.NUVIRA_MEMORY_DIR = memDir;
});

afterAll(() => {
  process.chdir(ORIG_CWD);
  resetWorkspaceStore();
  if (ORIG_CONFIG_DIR === undefined) delete process.env.NUVIRA_CONFIG_DIR;
  else process.env.NUVIRA_CONFIG_DIR = ORIG_CONFIG_DIR;
  if (ORIG_MEMORY_DIR === undefined) delete process.env.NUVIRA_MEMORY_DIR;
  else process.env.NUVIRA_MEMORY_DIR = ORIG_MEMORY_DIR;
  rmSync(root, { recursive: true, force: true });
});

beforeEach(() => {
  process.chdir(projectDir);
  clearLongFormJobs();
  clearUnattendedJobs();
});

afterEach(() => {
  process.chdir(ORIG_CWD);
  vi.restoreAllMocks();
});

/** The hybrid ask: a book, as a website, with narration. */
const WEB_BOOK_GOAL =
  'develop a web-based interactive book — a 20 page story called Mahagatha with voice narration for every chapter, ' +
  'presented as a website I can open in the browser';

/** The reasoner's live answer for an authored ask: a Python script. */
const MISFRAMED_DECISION = JSON.stringify({
  language: 'python',
  framework: 'none',
  platform: 'cli',
  architecture: 'multi-file',
  dependencies: ['os'],
  buildCommand: 'none',
  deliverable: 'markdown_file',
  constraints: ['Must write the story into Mahagatha.md'],
  isGreenfield: true,
  confidence: 0.9,
  reasoning: 'A Python script is the most efficient way to write the chapters.',
});

/** The planner's live answer: zero prose steps. */
const MISFRAMED_PLAN = JSON.stringify([
  { id: 'step-01', description: 'Create a Python script that writes the story', agentType: 'writer', complexity: 'moderate', dependsOn: [] },
  { id: 'step-02', description: 'Run the Python script', agentType: 'runner', complexity: 'simple', dependsOn: ['step-01'] },
]);

/** A prompt-aware fake: hostile decision layers, real prose, real site files. */
function bookProvider() {
  const prompts: string[] = [];
  const generate = vi.fn(async (prompt: string) => {
    prompts.push(prompt);
    if (/senior software architect/.test(prompt)) return MISFRAMED_DECISION;
    if (/agentType: One of/.test(prompt)) return MISFRAMED_PLAN;
    if (/You are an author/.test(prompt)) {
      const unit = /unit (\d+) of (\d+)/.exec(prompt);
      const n = unit ? unit[1] : '?';
      return `Chapter ${n} of Mahagatha. `.repeat(4) + 'The lamp guttered in the hall as the door closed. '.repeat(90);
    }
    // Every code-writing step. Deliberately a UNION of the deliverable's files
    // rather than a per-step match: the writer's prompt embeds the whole task
    // plan as well as the project files, so every step's prompt contains every
    // other step's filenames — a per-step match is impossible to make reliable
    // here. What each step is SUPPOSED to produce is asserted in
    // tests/agents/composite-plan.test.ts; this test is about what happens
    // end to end when the steps run.
    return [
      '```filepath:site/index.html',
      '<!doctype html><html><head><link rel="stylesheet" href="styles.css"></head><body>',
      '<nav id="toc"></nav><main id="chapter"></main>',
      '<button id="read-aloud">Read aloud</button>',
      '<script src="chapters.js"></script><script src="reader.js"></script>',
      '</body></html>',
      '```',
      '```filepath:site/styles.css',
      '.book { max-width: 40rem; margin: 0 auto; }',
      '```',
      '```filepath:site/reader.js',
      '// Reads the chapters in content/chapters/ at load time and renders one at a time.',
      '```',
      '```filepath:site/chapters.js',
      '// Enumerated at load time from content/chapters/.',
      'export const chapterDir = "content/chapters/";',
      '```',
      '```filepath:tools/narrate.py',
      'import os  # optional high-quality narration',
      '```',
    ].join('\n');
  });
  return { generate, prompts };
}

const siteDir = () => join(projectDir, 'site');
const chaptersDir = () => join(projectDir, 'content', 'chapters');

describe('E2E — the web-based interactive book ask', () => {
  it('plans PHASES, writes real content, and its own verify step FAILS while the book is unfinished', async () => {
    const fake = bookProvider();
    vi.spyOn(ProviderFactory, 'createProvider').mockImplementation(() => fake as never);

    // `useToolCalling: false` drives the one-shot writer (the prose path is
    // exempt from tool-calling anyway): a scripted provider cannot speak the
    // read→propose_change protocol, and this test is about the PLAN and the
    // verification gate, not about the tool loop.
    const result = await new Orchestrator().execute(WEB_BOOK_GOAL, {
      provider: 'local',
      model: 'test-model',
      verbose: false,
      useToolCalling: false,
    });

    // ── 1. The hybrid was planned as phases, not as a Python generator ────
    const composite = result.agentResults.find((a) => a.agent === 'CompositePlanner');
    expect(composite).toBeDefined();
    expect(composite!.summary).toMatch(/step\(s\) planned/);

    // ── 2. The SHAPE exists and opens from disk ───────────────────────────
    expect(existsSync(join(siteDir(), 'index.html'))).toBe(true);
    expect(existsSync(join(siteDir(), 'styles.css'))).toBe(true);
    expect(existsSync(join(siteDir(), 'reader.js'))).toBe(true);
    expect(existsSync(join(siteDir(), 'chapters.js'))).toBe(true);
    const html = readFileSync(join(siteDir(), 'index.html'), 'utf-8');
    expect(html).toMatch(/reader\.js/);
    // the narration control is the BROWSER's — nothing to install
    expect(html).toMatch(/read-aloud/);

    // ── 3. The CONTENT is real prose, one bounded file per unit ───────────
    const chapters = readdirSync(chaptersDir()).filter((f) => f.endsWith('.md')).sort();
    expect(chapters).toEqual([
      '01-chapter-1.md',
      '02-chapter-2.md',
      '03-chapter-3.md',
      '04-chapter-4.md',
    ]);
    for (const f of chapters) {
      expect(countWords(readFileSync(join(chaptersDir(), f), 'utf-8')), f).toBeGreaterThan(120);
    }

    // ── 4. The OPTIONAL service was produced, and nothing Python was required
    expect(existsSync(join(projectDir, 'tools', 'narrate.py'))).toBe(true);

    // ── 5. The verify step RAN and FAILED — the book is 4 of 8 units ──────
    // This is the honest gate: the site exists, four chapters exist, and the
    // assembled book does not. A green summary here would be a lie.
    expect(result.success).toBe(false);
    expect(existsSync(join(projectDir, 'content', 'book.md'))).toBe(false);

    // ── 6. …and the run says so, and hands the rest to the surface ────────
    expect(result.pendingWork).toBeDefined();
    expect(result.pendingWork!.kind).toBe('phased');
    expect(result.pendingWork!.percent).toBeGreaterThan(0);
    expect(result.pendingWork!.percent).toBeLessThan(100);
    expect(result.pendingWork!.expectedArtifacts).toEqual(
      expect.arrayContaining(['content/book.md', 'site/index.html', 'site/chapters.js', 'tools/narrate.py']),
    );
    // The continuation re-runs the ORIGINAL ask (phases are re-derived against
    // the ledger); it never asks the user for a magic word.
    expect(result.pendingWork!.continuationPrompt).toBe(WEB_BOOK_GOAL);
    expect(result.summary).not.toMatch(/reply\s*"continue"/i);
  });

  it('finishes on the CONTINUATION and its own verify step now PASSES', async () => {
    const fake = bookProvider();
    vi.spyOn(ProviderFactory, 'createProvider').mockImplementation(() => fake as never);
    const orchestrator = new Orchestrator();

    const opts = { provider: 'local', model: 'test-model', verbose: false, useToolCalling: false };
    const first = await orchestrator.execute(WEB_BOOK_GOAL, opts);
    expect(first.pendingWork).toBeDefined();

    // ── G14: the continuation does not re-decide the design ──────────────
    // This is the case `isContinuationAsk('continue')` would MISS: a composite
    // continuation re-sends the ORIGINAL goal, so only the LEDGER can tell us
    // this is a continuation. Neither design layer may be called again.
    const reasonerCalls = () => fake.prompts.filter((p) => /senior software architect/.test(p)).length;
    const plannerCalls = () => fake.prompts.filter((p) => /agentType: One of/.test(p)).length;
    const reasonerBefore = reasonerCalls();
    const plannerBefore = plannerCalls();
    expect(reasonerBefore).toBeGreaterThan(0);

    // The surface drives the continuation with exactly what it was handed.
    const second = await new Orchestrator().execute(first.pendingWork!.continuationPrompt, opts);
    expect(reasonerCalls()).toBe(reasonerBefore);
    expect(plannerCalls()).toBe(plannerBefore);
    expect(second.agentResults.find((a) => a.agent === 'Reasoner')!.summary).toMatch(/Skipped/);
    expect(second.agentResults.find((a) => a.agent === 'Planner')!.summary).toMatch(/Skipped/);

    // Every unit written → the document is assembled deterministically.
    const chapters = readdirSync(chaptersDir()).filter((f) => f.endsWith('.md'));
    expect(chapters).toHaveLength(8);
    const book = join(projectDir, 'content', 'book.md');
    expect(existsSync(book)).toBe(true);
    expect(countWords(readFileSync(book, 'utf-8'))).toBeGreaterThan(2_000);

    // The ledger is complete and the deliverable is measurably finished.
    const job = findLatestJob(process.cwd())!;
    expect(job.sections.every((s) => s.status === 'done')).toBe(true);

    // The verify step ran against a finished deliverable and SUCCEEDED, so this
    // run is allowed to report success — and there is no work left to hand off.
    expect(second.success).toBe(true);
    expect(second.pendingWork).toBeUndefined();
  });
});
