/**
 * Docker Management Skill — Comprehensive Docker operations guide.
 *
 * Teaches the agent how to:
 * - Manage container lifecycle (run, stop, start, restart, rm)
 * - Interact with containers (exec, logs, inspect, stats)
 * - Manage images (build, pull, push, tag, rmi)
 * - Work with Docker Compose
 * - Manage volumes and networks
 * - Handle disk usage and cleanup
 * - Debug container issues
 *
 * Hermes equivalent: optional-skills/devops/docker-management/SKILL.md
 */

import type { Skill } from '../learning/skill-types.js';

const DOCKER_MANAGEMENT_ID = 'skill-docker-management';
const DOCKER_CREATED_AT = 1_756_000_000_000;

export const dockerManagementSkill: Skill = {
  id: DOCKER_MANAGEMENT_ID,
  name: 'docker-management',
  description:
    'Manage Docker containers, images, volumes, networks, and Compose stacks. Use when the goal is to run, stop, restart, inspect, or debug Docker containers; build, pull, push, or clean up images; manage Docker Compose services; work with volumes or networks; check disk usage; or debug container issues. Also use for Dockerfile optimization and container health monitoring.',
  version: '1.0.0',
  goalPattern:
    'docker container image compose volume network build pull push run stop start restart exec logs inspect stats cleanup prune disk debug dockerfile optimization health',
  steps: [
    {
      agentType: 'context-gatherer',
      description: [
        'Verify Docker is available and running:',
        '```bash\ndocker --version && docker compose version\ndocker info --format "{{.ServerVersion}}"\n```',
        'Identify the domain of the request:',
        '- Container lifecycle → run, stop, start, restart, rm, pause/unpause',
        '- Container interaction → exec, cp, logs, inspect, stats',
        '- Image management → build, pull, push, tag, rmi, save/load',
        '- Docker Compose → up, down, ps, logs, exec, build, config',
        '- Volumes & networks → create, inspect, rm, prune, connect',
        '- Troubleshooting → log analysis, exit codes, resource issues',
        '- Disk usage → system df, prune, cleanup',
      ].join('\n'),
      dependsOn: [],
    },
    {
      agentType: 'runner',
      description: [
        'Execute the appropriate Docker operations. Key commands:',
        '',
        '## Container Lifecycle',
        '```bash',
        '# Run a new container (detached)',
        'docker run -d --name web -p 8080:80 nginx',
        '',
        '# Run with environment variables',
        'docker run -d -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=mydb --name db postgres:16',
        '',
        '# Run with persistent data (named volume)',
        'docker run -d -v mydata:/var/lib/postgresql/data --name db postgres:16',
        '',
        '# Stop + remove',
        'docker stop NAME && docker rm NAME',
        '',
        '# Force remove (even if running)',
        'docker rm -f NAME',
        '',
        '# Restart with timeout',
        'docker restart -t 10 NAME',
        '```',
        '',
        '## Container Interaction',
        '```bash',
        '# Shell into container',
        'docker exec -it NAME /bin/sh',
        '',
        '# View logs (follow)',
        'docker logs --tail 50 -f NAME',
        '',
        '# Inspect container details',
        'docker inspect NAME',
        '',
        '# Resource stats',
        'docker stats --no-stream',
        '',
        '# Copy files to/from container',
        'docker cp NAME:/path/to/file ./local/path',
        'docker cp ./local/path NAME:/path/in/container',
        '```',
        '',
        '## Image Management',
        '```bash',
        '# Build image',
        'docker build -t myapp:latest .',
        '',
        '# Build with no cache',
        'docker build --no-cache -t myapp:latest .',
        '',
        '# Pull image',
        'docker pull node:20-slim',
        '',
        '# List images',
        'docker images',
        '',
        '# Remove image',
        'docker rmi IMAGE',
        '',
        '# Remove dangling images',
        'docker image prune -f',
        '```',
        '',
        '## Docker Compose',
        '```bash',
        '# Start services (detached)',
        'docker compose up -d',
        '',
        '# Start with rebuild',
        'docker compose up -d --build',
        '',
        '# Stop and remove',
        'docker compose down',
        '',
        '# Stop and remove volumes',
        'docker compose down -v',
        '',
        '# View status',
        'docker compose ps',
        '',
        '# View logs',
        'docker compose logs -f SERVICE',
        '',
        '# Execute in service',
        'docker compose exec SERVICE COMMAND',
        '',
        '# Build specific service',
        'docker compose build SERVICE',
        '',
        '# Validate compose file',
        'docker compose config',
        '```',
        '',
        '## Volumes & Networks',
        '```bash',
        '# List volumes',
        'docker volume ls',
        '',
        '# Create volume',
        'docker volume create myvolume',
        '',
        '# Inspect volume',
        'docker volume inspect myvolume',
        '',
        '# Remove volume',
        'docker volume rm myvolume',
        '',
        '# Prune unused volumes',
        'docker volume prune -f',
        '',
        '# List networks',
        'docker network ls',
        '',
        '# Create network',
        'docker network create mynetwork',
        '',
        '# Connect container to network',
        'docker network connect mynetwork NAME',
        '',
        '# Disconnect from network',
        'docker network disconnect mynetwork NAME',
        '```',
        '',
        '## Disk Usage & Cleanup',
        '```bash',
        '# Check disk usage',
        'docker system df',
        '',
        '# Detailed disk usage',
        'docker system df -v',
        '',
        '# Full cleanup (dangling images + stopped containers + unused volumes)',
        'docker system prune -af --volumes',
        '',
        '# Remove stopped containers',
        'docker container prune -f',
        '',
        '# Remove unused images',
        'docker image prune -af',
        '',
        '# Remove build cache',
        'docker builder prune -f',
        '```',
        '',
        '## Troubleshooting',
        '```bash',
        '# Check container exit code',
        'docker inspect NAME --format="{{.State.ExitCode}}"',
        '',
        '# View container events',
        'docker events --filter container=NAME',
        '',
        '# Check container resource usage',
        'docker stats --no-stream NAME',
        '',
        '# View container process list',
        'docker top NAME',
        '',
        '# Check Docker daemon logs',
        'docker info',
        '',
        '# Debug with temporary container',
        'docker run --rm -it IMAGE /bin/sh',
        '```',
        '',
        '## Dockerfile Optimization',
        '```bash',
        '# Use multi-stage builds',
        '# FROM node:20 AS builder',
        '# RUN npm ci && npm run build',
        '# FROM node:20-slim',
        '# COPY --from=builder /app/dist ./dist',
        '',
        '# Order layers from least to most frequently changing',
        '# Use .dockerignore to exclude node_modules, .git, etc.',
        '# Pin base image versions for reproducibility',
        '# Use COPY instead of ADD (unless you need tar extraction)',
        '# Combine RUN commands to reduce layers',
        '```',
      ].join('\n'),
      dependsOn: ['step-0'],
    },
    {
      agentType: 'reviewer',
      description: [
        'Verify the Docker operations:',
        '- Containers are in expected state (running/stopped)',
        '- Images are built/pulled successfully',
        '- Compose services are up and healthy',
        '- Volumes are created and mounted correctly',
        '- No orphaned resources (use docker system df)',
        '- Disk usage is within acceptable limits',
      ].join('\n'),
      dependsOn: ['step-1'],
    },
  ],
  parameters: [
    {
      name: 'action',
      description: 'Docker action to perform: run | stop | start | restart | exec | logs | build | pull | compose-up | compose-down | compose-ps | disk-usage | cleanup | health',
      type: 'choice',
      required: true,
      options: ['run', 'stop', 'start', 'restart', 'exec', 'logs', 'build', 'pull', 'compose-up', 'compose-down', 'compose-ps', 'disk-usage', 'cleanup', 'health'],
    },
    {
      name: 'target',
      description: 'Container name, image name, or compose project directory',
      type: 'string',
      required: true,
    },
    {
      name: 'command',
      description: 'Command to execute in container (for exec action)',
      type: 'string',
      required: false,
    },
  ],
  tags: ['docker', 'containers', 'compose', 'devops', 'infrastructure'],
  sourceTrajectoryIds: ['bundled'],
  qualityScore: 0.9,
  usageCount: 0,
  createdAt: DOCKER_CREATED_AT,
  lastUsedAt: DOCKER_CREATED_AT,
};

/**
 * Container Supervision Skill — Monitor and supervise container health.
 *
 * Teaches the agent how to:
 * - Monitor container health status
 * - Auto-restart unhealthy containers
 * - Log container events
 * - Manage container restart policies
 *
 * Hermes equivalent: optional-skills/devops/hermes-s6-container-supervision/SKILL.md
 */

const CONTAINER_SUPERVISION_ID = 'skill-container-supervision';
const SUPERVISION_CREATED_AT = 1_756_000_000_000;

export const containerSupervisionSkill: Skill = {
  id: CONTAINER_SUPERVISION_ID,
  name: 'container-supervision',
  description:
    'Monitor and supervise Docker container health: check health status, configure restart policies, set up health checks, auto-restart unhealthy containers, and log container events. Use when the goal is to ensure containers stay running and recover from failures.',
  version: '1.0.0',
  goalPattern:
    'docker container health supervision monitoring restart policy auto-restart unhealthy healthcheck events logging',
  steps: [
    {
      agentType: 'context-gatherer',
      description: [
        'Check container health status:',
        '```bash',
        '# Check all containers health',
        'docker ps --format "{{.Names}}: {{.Status}}"',
        '',
        '# Inspect health check details',
        'docker inspect NAME --format="{{json .State.Health}}" | jq',
        '',
        '# Check restart count',
        'docker inspect NAME --format="{{.State.RestartCount}}"',
        '',
        '# Check restart policy',
        'docker inspect NAME --format="{{.HostConfig.RestartPolicy.Name}}"',
        '```',
        '',
        'Identify containers that need supervision:',
        '- Containers with health checks configured',
        '- Containers with restart policy',
        '- Containers that have restarted multiple times',
        '- Containers with high resource usage',
      ].join('\n'),
      dependsOn: [],
    },
    {
      agentType: 'runner',
      description: [
        'Set up container supervision:',
        '',
        '## Health Check Configuration',
        '```bash',
        '# Add health check to running container (via docker update)',
        'docker update --health-cmd="curl -f http://localhost/ || exit 1" \\',
        '  --health-interval=30s \\',
        '  --health-timeout=5s \\',
        '  --health-retries=3 \\',
        '  --health-start-period=10s \\',
        '  NAME',
        '',
        '# In Dockerfile:',
        '# HEALTHCHECK --interval=30s --timeout=5s --retries=3 \\',
        '#   CMD curl -f http://localhost/ || exit 1',
        '```',
        '',
        '## Restart Policies',
        '```bash',
        '# Set restart policy',
        'docker update --restart=unless-stopped NAME',
        '',
        '# Policies:',
        '# no          - Never restart (default)',
        '# on-failure  - Restart only on non-zero exit code',
        '# always      - Always restart',
        '# unless-stopped - Always restart unless manually stopped',
        '```',
        '',
        '## Auto-Restart Unhealthy Containers',
        '```bash',
        '# Check for unhealthy containers and restart them',
        'docker ps --filter "health=unhealthy" --format "{{.Names}}" | \\',
        '  xargs -I {} docker restart {}',
        '',
        '# Continuous monitoring script',
        'while true; do',
        '  unhealthy=$(docker ps --filter "health=unhealthy" --format "{{.Names}}")',
        '  for c in $unhealthy; do',
        '    echo "$(date): Restarting unhealthy container: $c"',
        '    docker restart "$c"',
        '  done',
        '  sleep 60',
        'done',
        '```',
        '',
        '## Container Event Logging',
        '```bash',
        '# View container events',
        'docker events --filter container=NAME',
        '',
        '# View events for last hour',
        'docker events --since 1h --filter container=NAME',
        '',
        '# Log to file',
        'docker events --format "{{json .}}" > container-events.jsonl',
        '```',
      ].join('\n'),
      dependsOn: ['step-0'],
    },
    {
      agentType: 'reviewer',
      description: [
        'Verify container supervision:',
        '- Health checks are configured and reporting status',
        '- Restart policies are set correctly',
        '- Unhealthy containers are being restarted',
        '- Container events are being logged',
        '- No containers are in a crash loop',
      ].join('\n'),
      dependsOn: ['step-1'],
    },
  ],
  parameters: [
    {
      name: 'action',
      description: 'Supervision action: check-health | set-restart-policy | auto-restart | monitor-events',
      type: 'choice',
      required: true,
      options: ['check-health', 'set-restart-policy', 'auto-restart', 'monitor-events'],
    },
    {
      name: 'container',
      description: 'Container name (required for most actions)',
      type: 'string',
      required: false,
    },
  ],
  tags: ['docker', 'containers', 'health', 'supervision', 'monitoring'],
  sourceTrajectoryIds: ['bundled'],
  qualityScore: 0.9,
  usageCount: 0,
  createdAt: SUPERVISION_CREATED_AT,
  lastUsedAt: SUPERVISION_CREATED_AT,
};

/** Export both Docker skills. */
export const DOCKER_SKILLS: Skill[] = [
  dockerManagementSkill,
  containerSupervisionSkill,
];
