/**
 * Inline Code Suggestions — Provides agent-generated inline code completions
 * as the user types, similar to GitHub Copilot.
 *
 * Uses VS Code's InlineCompletionItemProvider API to show suggestions
 * in the editor. Suggestions are generated by the agent-nuvira CLI.
 *
 * Features:
 * - Triggered on typing pause (debounced)
 * - Context-aware: uses surrounding code + file language
 * - Multi-line completions
 * - Configurable enable/disable via settings
 * - No suggestions in certain contexts (strings, comments — basic detection)
 */

import * as vscode from 'vscode';
import { spawn } from 'node:child_process';
import type { ExtensionConfig } from './types.js';
import { buildSuggestionPrompt, parseSuggestion } from './inlineSuggestUtils.js';

// ─── Constants ──────────────────────────────────────────────────────────────

/** Debounce delay in ms before triggering a suggestion */
const DEBOUNCE_MS = 800;

/** Max chars of context to send (only the needed slice is actually sent) */
const MAX_CONTEXT_CHARS = 600;

/** File extensions for which suggestions are enabled */
const SUPPORTED_EXTENSIONS = new Set([
  '.ts', '.js', '.tsx', '.jsx', '.py', '.go', '.rs', '.java',
  '.rb', '.php', '.c', '.cpp', '.h', '.hpp', '.cs', '.swift',
  '.kt', '.scala', '.vue', '.svelte', '.mjs', '.cjs',
]);

// ─── InlineSuggestProvider ──────────────────────────────────────────────────

export class InlineSuggestProvider implements vscode.InlineCompletionItemProvider {
  private config: ExtensionConfig;
  private debounceTimer: ReturnType<typeof setTimeout> | null = null;
  private pendingRequest: AbortController | null = null;
  /** Resolver for the previous pending debounce, to prevent promise leaks */
  private pendingResolver: ((value: vscode.InlineCompletionItem[]) => void) | null = null;

  constructor(config: ExtensionConfig) {
    this.config = config;
  }

  /**
   * Called by VS Code when it needs inline completions.
   * We debounce and only provide suggestions after a typing pause.
   */
  async provideInlineCompletionItems(
    document: vscode.TextDocument,
    position: vscode.Position,
    context: vscode.InlineCompletionContext,
    token: vscode.CancellationToken,
  ): Promise<vscode.InlineCompletionItem[] | vscode.InlineCompletionList> {
    // Check if suggestions are enabled for this file type
    const ext = document.fileName.slice(document.fileName.lastIndexOf('.'));
    if (!SUPPORTED_EXTENSIONS.has(ext)) {
      return [];
    }

    // Don't suggest on explicit trigger if we're just deleting
    if (context.triggerKind === vscode.InlineCompletionTriggerKind.Automatic) {
      // Check if the last edit was a deletion (don't suggest on delete)
      const lastLine = document.lineAt(Math.max(0, position.line - 1));
      if (lastLine.text.trim().length === 0 && position.character === 0) {
        return []; // Empty line at start — likely a deletion
      }
    }

    // Cancel any pending request
    if (this.pendingRequest) {
      this.pendingRequest.abort();
    }
    this.pendingRequest = new AbortController();

    // Debounce: resolve previous pending promise (to prevent leaks) and set new one
    if (this.pendingResolver) {
      this.pendingResolver([]);
      this.pendingResolver = null;
    }

    const result = new Promise<vscode.InlineCompletionItem[]>((resolve) => {
      this.pendingResolver = resolve;

      if (this.debounceTimer) {
        clearTimeout(this.debounceTimer);
      }

      this.debounceTimer = setTimeout(async () => {
        this.pendingResolver = null;

        if (token.isCancellationRequested) {
          resolve([]);
          return;
        }

        try {
          const suggestions = await this.generateSuggestion(document, position, token);
          resolve(suggestions);
        } catch {
          resolve([]);
        }
      }, DEBOUNCE_MS);
    });

    return result;
  }

  /**
   * Generate a code suggestion by asking the CLI.
   */
  private async generateSuggestion(
    document: vscode.TextDocument,
    position: vscode.Position,
    token: vscode.CancellationToken,
  ): Promise<vscode.InlineCompletionItem[]> {
    // Get context: lines before and at cursor
    const contextLines = this.getContextLines(document, position);

    if (!contextLines) {
      return [];
    }

    // Build the prompt for the CLI
    const fileExtension = document.fileName.split('.').pop() || '';
    const languageId = document.languageId;
    const prompt = buildSuggestionPrompt(contextLines, languageId, fileExtension);

    // Call the CLI for a suggestion
    try {
      const suggestion = await this.callCLIForSuggestion(prompt, token);

      if (!suggestion || token.isCancellationRequested) {
        return [];
      }

      // Parse the suggestion into completion items
      const items = parseSuggestion(suggestion, position);
      return items;
    } catch {
      return [];
    }
  }

  /**
   * Get context lines around the cursor position.
   * Returns text before the cursor (for completion prefix).
   */
  private getContextLines(
    document: vscode.TextDocument,
    position: vscode.Position,
  ): { beforeCursor: string; afterCursor: string; currentLinePrefix: string } | null {
    const maxChars = MAX_CONTEXT_CHARS;

    // Get text before cursor (up to maxChars)
    const beforeRange = new vscode.Range(
      new vscode.Position(Math.max(0, position.line - 50), 0),
      position,
    );
    const beforeText = document.getText(beforeRange);
    const beforeCursor = beforeText.slice(-maxChars);

    // Get text after cursor (up to 10 lines)
    const afterEndLine = Math.min(document.lineCount - 1, position.line + 10);
    const afterRange = new vscode.Range(position, new vscode.Position(afterEndLine, 0));
    const afterCursor = document.getText(afterRange);

    // Get current line prefix (text from line start to cursor)
    const currentLinePrefix = document.lineAt(position.line).text.slice(0, position.character);

    return { beforeCursor, afterCursor, currentLinePrefix };
  }

  /**
   * Call the CLI to get a suggestion.
   */
  private async callCLIForSuggestion(
    prompt: string,
    token: vscode.CancellationToken,
  ): Promise<string | null> {
    const cliPath = this.config.cliPath || 'buff';
    const args = ['chat', prompt, '--stream'];

    // Handle 'npx' prefix
    let command: string;
    let spawnArgs: string[];
    if (cliPath.startsWith('npx ')) {
      command = 'npx';
      spawnArgs = [cliPath.slice(4), ...args];
    } else {
      command = cliPath;
      spawnArgs = args;
    }

    // Add provider/model if configured
    if (this.config.defaultProvider) {
      spawnArgs.push('--provider', this.config.defaultProvider);
    }
    if (this.config.defaultModel) {
      spawnArgs.push('--model', this.config.defaultModel);
    }

    return new Promise<string | null>((resolve) => {
      const child = spawn(command, spawnArgs, {
        stdio: ['pipe', 'pipe', 'pipe'],
        env: { ...process.env, FORCE_COLOR: '0' },
        timeout: 10_000, // 10s timeout for suggestions
      });

      let output = '';

      child.stdout?.on('data', (data: Buffer) => {
        output += data.toString();
      });

      child.stderr?.on('data', () => {
        // Swallow stderr for inline suggestions
      });

      child.on('close', (code) => {
        if (token.isCancellationRequested) {
          resolve(null);
          return;
        }

        const trimmed = output.trim();
        if (trimmed && trimmed !== 'NONE' && code !== null) {
          resolve(trimmed);
        } else {
          resolve(null);
        }
      });

      child.on('error', () => {
        resolve(null);
      });

      // Cancel on token cancellation
      token.onCancellationRequested(() => {
        child.kill('SIGTERM');
      });
    });
  }

  /**
   * Update config when settings change.
   */
  updateConfig(config: ExtensionConfig): void {
    this.config = config;
  }
}
