/**
 * @agent-nuvira/sdk/scaffold — Scaffolding command for creating custom agent projects.
 *
 * Generates a complete, ready-to-extend agent package with:
 * - TypeScript configuration
 * - A custom agent class extending {@link Agent}
 * - Unit tests using the {@link testing} utilities
 * - Package.json with build/test scripts
 *
 * @module @agent-nuvira/sdk/scaffold
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

// ─── Template Types ─────────────────────────────────────────────────────────

/** Template type to scaffold */
export type ScaffoldTemplate = 'basic-agent' | 'full-agent' | 'agent-pack';

/** Options for scaffolding */
export interface ScaffoldOptions {
  /** Output directory for the new agent project */
  outDir: string;
  /** Name of the agent class (PascalCase, e.g. "CodeFormatter") */
  agentName: string;
  /** Description of what the agent does */
  description: string;
  /** Template type (default: 'full-agent') */
  template?: ScaffoldTemplate;
  /** Agent type identifier for task plans (default: kebab-case of agentName) */
  agentType?: string;
}

// ─── Agent Name Helpers ─────────────────────────────────────────────────────

/** Convert PascalCase to kebab-case (e.g. "CodeFormatter" → "code-formatter") */
function toKebabCase(pascal: string): string {
  return pascal
    .replace(/([A-Z])/g, '-$1')
    .toLowerCase()
    .replace(/^-/, '');
}

/** Convert PascalCase to camelCase (e.g. "CodeFormatter" → "codeFormatter") */
function toCamelCase(pascal: string): string {
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

// ─── Templates ──────────────────────────────────────────────────────────────

const PACKAGE_JSON_TEMPLATE = (opts: ScaffoldOptions) => `{
  "name": "${toKebabCase(opts.agentName)}-agent",
  "version": "0.1.0",
  "description": "${opts.description}",
  "type": "module",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "tsc",
    "dev": "tsc --watch",
    "test": "vitest run",
    "test:watch": "vitest"
  },
  "dependencies": {
    "@agent-nuvira/sdk": "^1.0.0"
  },
  "devDependencies": {
    "typescript": "^5.3.0",
    "vitest": "^1.0.0"
  }
}`;

const TS_CONFIG_TEMPLATE = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "dist"]
}`;

const AGENT_SRC_TEMPLATE = (opts: ScaffoldOptions) => {
  const agentType = opts.agentType || toKebabCase(opts.agentName);
  return `/**
 * ${opts.agentName} — ${opts.description}
 *
 * Generated by \`buff sdk scaffold\`
 */

import { Agent, type AgentContext, type AgentResult, type LLMCallFn } from '@agent-nuvira/sdk';

export class ${opts.agentName} extends Agent {
  readonly name = '${opts.agentName}';
  readonly description = '${opts.description}';

  async execute(context: AgentContext, callLLM: LLMCallFn): Promise<AgentResult> {
    // ── Read inputs from context ───────────────────────────────────────
    const goal = context.goal;
    const files = context.artifacts;

    // ── Build a prompt for the LLM ─────────────────────────────────────
    const prompt = \`You are the ${opts.agentName} agent.
Goal: \${goal}

Files:
\${files.map(f => \`- \${f.path}: \${f.description}\`).join('\\\\n') || '(No files provided)'}

Please complete the task described in the goal.\`;

    // ── Call the LLM ───────────────────────────────────────────────────
    const response = await callLLM(prompt, {
      temperature: 0.3,
      maxTokens: 2048,
    });

    // ── Process and return results ─────────────────────────────────────
    return {
      success: true,
      summary: \`\${this.name} completed: \${goal.slice(0, 60)}\`,
      details: response,
    };
  }
}

/**
 * Agent descriptor for registering this agent in the system.
 * Export this to allow automatic registration.
 */
export const agentDescriptor = {
  AgentClass: ${opts.agentName},
  name: '${opts.agentName}',
  description: '${opts.description}',
  agentType: '${agentType}',
  tags: 'custom',
};
`;
};

const AGENT_INDEX_TEMPLATE = (opts: ScaffoldOptions) => `/**
 * ${opts.agentName} — Agent entry point.
 * Generated by \`buff sdk scaffold\`
 */

export { ${opts.agentName}, agentDescriptor } from './${toCamelCase(opts.agentName)}.js';
`;

const VITEST_CONFIG_TEMPLATE = `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
  },
});
`;

const AGENT_TEST_TEMPLATE = (opts: ScaffoldOptions) => `/**
 * ${opts.agentName} — Unit tests.
 * Generated by \`buff sdk scaffold\`
 */

import { describe, it, expect } from 'vitest';
import { ${opts.agentName} } from '../src/${toCamelCase(opts.agentName)}.js';
import {
  createMockContext,
  createMockLLM,
  createFailingMockLLM,
  runAgentTest,
  assertAgentSuccess,
  assertAgentFailure,
} from '@agent-nuvira/sdk/testing';

describe('${opts.agentName}', () => {
  const agent = new ${opts.agentName}();

  it('should return success with summary', async () => {
    const context = createMockContext({
      goal: 'Test the agent',
      artifacts: [
        { path: 'src/index.ts', content: 'console.log("hello")', description: 'Source file' },
      ],
    });
    const callLLM = createMockLLM('Task completed successfully');

    const result = await runAgentTest(agent, context, callLLM);

    assertAgentSuccess(result);
    expect(result.summary).toBeTruthy();
  });

  it('should handle errors gracefully', async () => {
    const context = createMockContext({ goal: 'Test error handling' });
    const callLLM = createFailingMockLLM(new Error('API error'));

    const result = await runAgentTest(agent, context, callLLM);

    assertAgentFailure(result);
    expect(result.error).toContain('API error');
  });

  it('should pass validation by default', () => {
    const context = createMockContext();
    const validation = agent.validate(context);
    expect(validation).toBe(true);
  });
});
`;

const AGENT_PACK_TEMPLATE = `# Agent Packages

This directory contains multiple custom agents that can be registered together.
Use \`buff sdk register\` to register all agents in a package.

## Adding an Agent

1. Create a new directory with your agent name
2. Add the agent source file extending \`Agent\`
3. Export an \`agentDescriptor\` object
4. Re-export from this package's \`index.ts\`
`;

const AGENT_PACK_INDEX_TEMPLATE = (opts: ScaffoldOptions) => `/**
 * ${opts.agentName} — Agent package entry point.
 * Generated by \`buff sdk scaffold\`
 */

// Re-export your custom agents here:
// export { MyAgent, agentDescriptor as myAgentDescriptor } from './my-agent/index.js';
// export { AnotherAgent, agentDescriptor as anotherAgentDescriptor } from './another-agent/index.js';
`;

// ─── File Writer ────────────────────────────────────────────────────────────

function writeFile(outDir: string, filePath: string, content: string): string {
  const fullPath = join(outDir, filePath);
  mkdirSync(join(outDir, dirname(filePath)), { recursive: true });
  writeFileSync(fullPath, content, 'utf-8');
  return fullPath;
}

function dirname(p: string): string {
  const idx = p.lastIndexOf('/');
  return idx >= 0 ? p.slice(0, idx) : '.';
}

// ─── Scaffold Command ───────────────────────────────────────────────────────

/**
 * Scaffold a new custom agent project.
 *
 * @returns An array of file paths that were created.
 *
 * @example
 * ```ts
 * const files = scaffold({
 *   outDir: './my-custom-agent',
 *   agentName: 'CodeFormatter',
 *   description: 'Formats source code according to project conventions',
 * });
 * console.log(\`Created \${files.length} files\`);
 * ```
 */
export function scaffold(options: ScaffoldOptions): string[] {
  const {
    outDir,
    agentName,
    description,
    template = 'full-agent',
    agentType,
  } = options;

  if (!agentName || !agentName.match(/^[A-Z][a-zA-Z0-9]*$/)) {
    throw new Error(
      `Invalid agent name "${agentName}". Must be in PascalCase (e.g. "CodeFormatter", "MyAgent").`,
    );
  }

  if (existsSync(outDir)) {
    throw new Error(`Output directory already exists: ${outDir}`);
  }

  const files: string[] = [];

  switch (template) {
    case 'basic-agent': {
      files.push(writeFile(outDir, 'package.json', PACKAGE_JSON_TEMPLATE({ ...options, description })));
      files.push(writeFile(outDir, 'tsconfig.json', TS_CONFIG_TEMPLATE));
      files.push(writeFile(outDir, `src/${toCamelCase(agentName)}.ts`, AGENT_SRC_TEMPLATE({ ...options, description })));
      files.push(writeFile(outDir, 'src/index.ts', AGENT_INDEX_TEMPLATE({ ...options, description })));
      break;
    }

    case 'full-agent': {
      files.push(writeFile(outDir, 'package.json', PACKAGE_JSON_TEMPLATE({ ...options, description })));
      files.push(writeFile(outDir, 'tsconfig.json', TS_CONFIG_TEMPLATE));
      files.push(writeFile(outDir, 'vitest.config.ts', VITEST_CONFIG_TEMPLATE));
      files.push(writeFile(outDir, `src/${toCamelCase(agentName)}.ts`, AGENT_SRC_TEMPLATE({ ...options, description })));
      files.push(writeFile(outDir, 'src/index.ts', AGENT_INDEX_TEMPLATE({ ...options, description })));
      files.push(writeFile(outDir, `tests/${toCamelCase(agentName)}.test.ts`, AGENT_TEST_TEMPLATE({ ...options, description })));
      break;
    }

    case 'agent-pack': {
      files.push(writeFile(outDir, 'README.md', AGENT_PACK_TEMPLATE));
      files.push(writeFile(outDir, 'src/index.ts', AGENT_PACK_INDEX_TEMPLATE({ ...options, description })));
      break;
    }

    default: {
      throw new Error(`Unknown template type: ${template}`);
    }
  }

  return files;
}

/**
 * List available scaffold templates with descriptions.
 */
export function listTemplates(): Array<{ name: string; description: string }> {
  return [
    {
      name: 'basic-agent',
      description: 'Minimal agent with package.json, tsconfig, and source file',
    },
    {
      name: 'full-agent',
      description: 'Complete agent with package.json, tsconfig, vitest, source, and unit tests',
    },
    {
      name: 'agent-pack',
      description: 'Multi-agent package structure for distributing multiple agents together',
    },
  ];
}
